services:
  - type: web
    name: my-service
    env: node
    buildCommand: npm install && npx playwright install --with-deps
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production